/**
 * @module server
 * @description Configures tools for the MCP Automation Server with stateful HITL gates.
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import {
  OKFDocumentService,
  OKFDocumentFactory,
  ApplicationStatus,
  mcpToolCallsCounter,
  mcpToolFailuresCounter,
  automationAttemptsCounter,
  automationApprovalRequiredCounter,
  automationSubmissionSuccessCounter,
} from '@ocf/core';
import { BrowserOrchestrator } from './automation/browser-orchestrator.js';
import { ApprovalStore } from './approval/approval-store.js';
import { auditLogger } from './audit/audit-log.js';
import { checkPolicy } from './policy/autonomy-policy.js';

const approvalStore = new ApprovalStore();

// Centralized approval store handles pending tokens

export class OCFMcpAutomationServer {
  private readonly server: McpServer;
  private readonly docService: OKFDocumentService;
  private readonly orchestrator: BrowserOrchestrator;

  constructor(docService: OKFDocumentService) {
    this.docService = docService;
    this.orchestrator = new BrowserOrchestrator();

    // Create the MCP server instance
    this.server = new McpServer({
      name: 'open-career-format-automation-server',
      version: '0.1.0',
    });

    this.registerTools();
  }

  getServerInstance(): McpServer {
    return this.server;
  }

  private registerTools(): void {
    // Tool: preview_application
    this.server.tool(
      'preview_application',
      {
        jobUrl: z.string().url().describe('The job posting vacancy URL to preview'),
      },
      async ({ jobUrl }) => {
        mcpToolCallsCounter.add(1);
        try {
          const platform = this.detectPlatform(jobUrl);
          return {
            content: [
              {
                type: 'text',
                text: JSON.stringify({
                  jobUrl,
                  platform,
                  requiredFields: ['first_name', 'last_name', 'email', 'resume_file', 'phone'],
                  estimatedAutonomyLevel: 'act-with-approval',
                }, null, 2),
              },
            ],
          };
        } catch (err: any) {
          mcpToolFailuresCounter.add(1);
          return { isError: true, content: [{ type: 'text', text: err.message }] };
        }
      }
    );

    // Tool: prepare_application
    this.server.tool(
      'prepare_application',
      {
        jobUrl: z.string().url().describe('The target job posting vacancy URL'),
      },
      async ({ jobUrl }) => {
        mcpToolCallsCounter.add(1);
        automationAttemptsCounter.add(1);
        automationApprovalRequiredCounter.add(1);
        const startTime = Date.now();
        const policy = checkPolicy('prepare_application');

        try {
          const context = await this.docService.getCareerContext();
          
          const pref = context.preferences[0];
          const roles = pref?.frontmatter['roles'] || [];
          
          const preparedFields = {
            rolesApplied: Array.isArray(roles) ? roles.join(', ') : 'Software Engineer',
            status: 'Draft',
          };

          const payload = { jobUrl, context, preparedFields };
          const token = approvalStore.generateToken('confirm_application_submission', payload);

          auditLogger.log({
            requestId: token,
            toolName: 'prepare_application',
            autonomyLevel: policy?.approvalMode === 'required' ? 'act-with-approval' : 'advise',
            approvalRequired: false,
            sideEffectLevel: policy?.sideEffectLevel || 'external-read',
            status: 'success',
            durationMs: Date.now() - startTime,
          });

          return {
            content: [
              {
                type: 'text',
                text: JSON.stringify({
                  ok: true,
                  message: 'Application pre-filled and locked. Explicit human authorization is required to submit.',
                  approvalToken: token,
                  autonomyLevel: 'act-with-approval',
                  preparedFields,
                }, null, 2),
              },
            ],
          };
        } catch (err: any) {
          mcpToolFailuresCounter.add(1);
          auditLogger.log({
            requestId: 'unknown',
            toolName: 'prepare_application',
            autonomyLevel: 'advise',
            approvalRequired: false,
            sideEffectLevel: 'external-read',
            status: 'failure',
            durationMs: Date.now() - startTime,
            details: { error: err.message }
          });
          return { isError: true, content: [{ type: 'text', text: err.message }] };
        }
      }
    );

    // Tool: confirm_application_submission
    this.server.tool(
      'confirm_application_submission',
      {
        approvalToken: z.string().describe('The validation token generated by prepare_application'),
        jobUrl: z.string().url().describe('The target job posting vacancy URL'),
        dryRun: z.boolean().optional().default(false),
      },
      async ({ approvalToken, jobUrl, dryRun }) => {
        mcpToolCallsCounter.add(1);
        const startTime = Date.now();
        const policy = checkPolicy('confirm_application_submission');

        try {
          // Re-fetch context to rebuild the exact payload that was hashed
          const context = await this.docService.getCareerContext();
          const pref = context.preferences[0];
          const roles = pref?.frontmatter['roles'] || [];
          const preparedFields = {
            rolesApplied: Array.isArray(roles) ? roles.join(', ') : 'Software Engineer',
            status: 'Draft',
          };

          const expectedPayload = { jobUrl, context, preparedFields };
          
          const isValid = approvalStore.validateAndConsume(approvalToken, 'confirm_application_submission', expectedPayload);

          if (!isValid) {
            const errorMsg = `Execution Blocked: Invalid, expired, or tampered approval token: ${approvalToken}`;
            auditLogger.log({
              requestId: approvalToken,
              toolName: 'confirm_application_submission',
              autonomyLevel: 'act-with-approval',
              approvalRequired: true,
              sideEffectLevel: policy?.sideEffectLevel || 'external-submit',
              status: 'blocked',
              durationMs: Date.now() - startTime,
              details: { reason: 'token_validation_failed' }
            });
            throw new Error(errorMsg);
          }
          
          const mode = process.env['AUTOMATION_RUNTIME_MODE'] || 'sandbox';
          if (mode !== 'explicit-authorized-live' && !dryRun) {
            const errorMsg = `Execution Blocked: AUTOMATION_RUNTIME_MODE is set to '${mode}'. Live application submissions are disabled unless mode is 'explicit-authorized-live' or dryRun is true.`;
            auditLogger.log({
              requestId: approvalToken,
              toolName: 'confirm_application_submission',
              autonomyLevel: 'act-with-approval',
              approvalRequired: true,
              sideEffectLevel: policy?.sideEffectLevel || 'external-submit',
              status: 'blocked',
              durationMs: Date.now() - startTime,
              details: { reason: 'runtime_mode_blocked' }
            });
            throw new Error(errorMsg);
          }

          // Trigger Playwright browser automation
          const result = await this.orchestrator.orchestrate(jobUrl, context, {
            headless: true,
            dryRun,
          });

          if (!result.success) {
            auditLogger.log({
              requestId: approvalToken,
              toolName: 'confirm_application_submission',
              autonomyLevel: 'act-with-approval',
              approvalRequired: true,
              sideEffectLevel: policy?.sideEffectLevel || 'external-submit',
              status: 'failure',
              durationMs: Date.now() - startTime,
              details: { error: 'automation_failed' }
            });
            return {
              isError: true,
              content: [{ type: 'text', text: `Automation execution failed: ${result.errors?.join('\n')}` }],
            };
          }

          // Create and save OKF Application Document if not just a dry run (or if dry run saving is desired)
          // The policy requires dry run to NOT generate a "success" state in terms of "Applied", so it's "Saved".
          const appDoc = OKFDocumentFactory.createApplication(
            result.company,
            result.jobTitle,
            jobUrl,
            {
              platform: result.platform,
              status: dryRun ? ApplicationStatus.Saved : ApplicationStatus.Applied,
              appliedAt: result.submittedAt,
            }
          );

          await this.docService.createDocument(appDoc);
          automationSubmissionSuccessCounter.add(1);

          auditLogger.log({
            requestId: approvalToken,
            toolName: 'confirm_application_submission',
            autonomyLevel: 'act-with-approval',
            approvalRequired: true,
            sideEffectLevel: policy?.sideEffectLevel || 'external-submit',
            status: 'success',
            durationMs: Date.now() - startTime,
          });

          return {
            content: [
              {
                type: 'text',
                text: JSON.stringify({
                  ok: true,
                  message: dryRun
                    ? 'Dry-run application completed successfully.'
                    : 'Job application successfully submitted and registered in OKF bundle.',
                  conceptId: appDoc.conceptId,
                }, null, 2),
              },
            ],
          };
        } catch (err: any) {
          mcpToolFailuresCounter.add(1);
          return { isError: true, content: [{ type: 'text', text: err.message }] };
        }
      }
    );

    // Tool: capture_job_posting
    this.server.tool('capture_job_posting', { jobUrl: z.string().url() }, async () => {
      mcpToolCallsCounter.add(1);
      return {
        isError: true,
        content: [{ type: 'text', text: 'NOT_IMPLEMENTED: Feature deferred.' }],
      };
    });

    // Tool: extract_platform_metadata
    this.server.tool('extract_platform_metadata', { jobUrl: z.string().url() }, async () => {
      mcpToolCallsCounter.add(1);
      return {
        isError: true,
        content: [{ type: 'text', text: 'NOT_IMPLEMENTED: Feature deferred.' }],
      };
    });
  }

  private detectPlatform(url: string): string {
    const lower = url.toLowerCase();
    if (lower.includes('linkedin')) return 'LinkedIn';
    if (lower.includes('gupy')) return 'Gupy';
    if (lower.includes('indeed')) return 'Indeed';
    return 'GenericPlatform';
  }
}
